name: DGMBENCH
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - absl-py==2.1.0
    - accelerate==1.6.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - alabaster==0.7.16
    - anyio==4.4.0
    - argcomplete==3.5.3
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - args==0.1.0
    - arrow==1.3.0
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - clint==0.5.1
    - cmake==3.31.4
    - colorlog==6.9.0
    - contourpy==1.3.2
    - cycler==0.12.1
    - datasets==3.5.1
    - defusedxml==0.7.1
    - dill==0.3.8
    - distlib==0.3.9
    - docutils==0.18.1
    - evaluate==0.4.3
    - fastcore==1.7.29
    - fastjsonschema==2.20.0
    - filelock==3.17.0
    - fonttools==4.57.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - gap-stat==2.0.1
    - ghapi==1.0.4
    - grpcio==1.70.0
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.30.2
    - imageio==2.37.0
    - imagesize==1.4.1
    - iniconfig==2.0.0
    - isoduration==20.11.0
    - Jinja2==3.1.4
    - joblib==1.4.2
    - jq==1.8.0
    - json5==0.9.25
    - jsonpointer==2.1
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-events==0.10.0
    - jupyterlab==4.2.4
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.27.3
    - jupyter-lsp==2.2.5
    - jupyter_server==2.14.2
    - jupyter_server_terminals==0.5.3
    - kiwisolver==1.4.8
    - kmeans1d==0.3.1
    - lazy_loader==0.4
    - lightning-utilities==0.12.0
    - lit==18.1.8
    - Markdown==3.7
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.5
    - matplotlib==3.10.1
    - mdurl==0.1.2
    - mistune==3.0.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - mypy-extensions==1.0.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - networkx==3.4.2
    - notebook==7.2.1
    - notebook_shim==0.2.4
    - nox==2023.4.22
    - numpy==2.2.5
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu11==2.21.5
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu11==11.8.86
    - nvidia-nvtx-cu12==12.6.77
    - overrides==7.7.0
    - pandas==2.2.3
    - pandocfilters==1.5.1
    - pillow==11.1.0
    - prometheus_client==0.20.0
    - protobuf==5.29.3
    - pyarrow==20.0.0
    - pybind11==2.13.6
    - pyDeprecate==0.3.2
    - pyparsing==3.1.2
    - pyre-extensions==0.0.32
    - pytest==7.4.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2025.2
    - PyYAML==6.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.5.3
    - rpds-py==0.20.0
    - safetensors==0.5.3
    - scikit-image==0.25.2
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - Send2Trash==1.8.3
    - sentencepiece==0.2.0
    - six==1.17.0
    - sniffio==1.3.1
    - snowballstemmer==2.2.0
    - soupsieve==2.6
    - Sphinx==7.3.7
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jquery==4.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sphinx-rtd-theme==1.3.0
    - sympy==1.14.0
    - tabulate==0.9.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - tifffile==2025.3.30
    - tinycss2==1.3.0
    - tokenizers==0.21.1
    - tomli==2.0.1
    - torch==2.7.0+cu118
    - torchaudio==2.7.0+cu118
    - torcheval==0.0.6
    - torchmetrics==0.9.3
    - torchtext==0.6.0
    - torchtnt==0.2.4
    - torchvision==0.22.0+cu118
    - tqdm==4.67.1
    - transformers==4.51.3
    - triton==3.3.0
    - types-python-dateutil==2.9.0.20240316
    - typing-inspect==0.9.0
    - tzdata==2025.2
    - uri-template==1.3.0
    - virtualenv==20.29.2
    - wcwidth==0.2.13
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - Werkzeug==3.1.3
    - xxhash==3.5.0
    - yarl==1.9.4
